# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and publish docker image

on:
  push:
    branches: master
    tags: 'v[0-9]+.[0-9]+'
  pull_request:
    branches: master

jobs:
  build_image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event.release.tag_name != '' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gtest-docker:latest,${{ secrets.DOCKERHUB_USERNAME }}/gtest-docker:${{ github.event.release.tag_name || 'default' }}
